# Generated by Django 6.0 on 2026-01-06 18:18

import apps.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('3e17fa10-53ef-407e-a5a4-b0b1ae74bc3d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
