# Generated by Django 6.0 on 2026-01-06 18:25

import apps.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_attendance_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_default=apps.models.base.GenRandomUUID(), default=uuid.UUID('5925338a-3dc3-4208-ad77-1bc0b47d6693'), editable=False, primary_key=True, serialize=False),
        ),
    ]
